FROM node:19-alpine3.17 as build-stage
ARG API_URL
ENV API_URL $API_URL
WORKDIR /app
COPY package.json /app/
COPY package-lock.json /app/
RUN npm install
COPY ./ /app/
RUN npm run build

FROM nginx:1.24.0-alpine3.17
COPY --from=build-stage /app/build/ /usr/share/nginx/html
# Copy the default nginx.conf provided by tiangolo/node-frontend
COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf
