version: '3.8'

services:
  bitpapa_bot:
    container_name: bitpapa_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8011:8003"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: [
      "uvicorn",
      "--host", "0.0.0.0",
      "--port", "8003",
      "--reload",
      "main:app"
    ]

  postgres:
    image: postgres:14-alpine3.17
    container_name: bitpapa_bot_postgres
    env_file:
      - ./.env
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - "25438:5432"

volumes:
  data-postgres:
