version: '3.8'

services:
  config_server:
    container_name: bitpapa_config_server
    build:
      context: ./app
      dockerfile: ../provision/Dockerfile.server
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./app:/app
    entrypoint: ./entrypoints/config_server.entrypoint.sh

  config_front:
    container_name: bitpapa_config_front
    build:
      context: ./config_front
      dockerfile: ../provision/Dockerfile.front
      args:
        REACT_APP_API_URL: ${API_URL}
    env_file:
      - ./.env
    command: [
      "nginx", "-g", "daemon off;"
    ]

  celery:
    container_name: bitpapa_celery
    build:
      context: ./app
      dockerfile: ../provision/Dockerfile.server
    env_file:
      - ./.env
    depends_on:
      - redis
      - config_server
    volumes:
      - ./app:/app
    entrypoint: ./entrypoints/celery.entrypoint.sh

  offer_updater:
    container_name: bitpapa_offer_updater
    build:
      context: ./app
      dockerfile: ../provision/Dockerfile.server
    env_file:
      - ./.env
    depends_on:
      - postgres
      - config_server
      - redis
    volumes:
      - ./app:/app
    entrypoint: ./entrypoints/offer_updater.entrypoint.sh

  min_price_updater:
    container_name: bitpapa_min_price_updater
    build:
      context: ./app
      dockerfile: ../provision/Dockerfile.server
    env_file:
      - ./.env
    depends_on:
      - postgres
      - config_server
      - redis
    volumes:
      - ./app:/app
    entrypoint: ./entrypoints/price_updater.entrypoint.sh

#  trade_handler:
#    container_name: bitpapa_trade_handler
#    build:
#      context: ./app
#      dockerfile: ../provision/Dockerfile.server
#    env_file:
#      - ./.env
#    depends_on:
#      - postgres
#      - config_server
#    volumes:
#      - ./app:/app
#    entrypoint: ./entrypoints/price_updater.entrypoint.sh

  nginx:
    image: nginx:latest
    container_name: bitpapa_nginx
    restart: unless-stopped
    depends_on:
      - config_server
      - config_front
    ports:
      - "8555:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  redis:
    image: redis:latest
    container_name: bitpapa_redis
    restart: always
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:14-alpine3.17
    container_name: bitpapa_bot_postgres
    env_file:
      - ./.env
    ports:
      - "25438:5432"
    volumes:
      - data-postgres:/var/lib/postgresql/data

volumes:
  data-postgres:
  redis-data:
