version: '3.8'

services:
  config_server:
    container_name: bitpapa_bot
    build:
      context: ./app
      dockerfile: ../provision/Dockerfile.server
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: [
      "uvicorn",
      "--host", "0.0.0.0",
      "--port", "8003",
      "--reload",
      "main:app"
    ]

  config_front:
    container_name: bitpapa_config_front
    build:
      context: ./config_front
      dockerfile: ../provision/Dockerfile.front
      args:
        REACT_APP_API_URL: ${API_URL}
    env_file:
      - ./.env
    command: [
      "nginx", "-g", "daemon off;"
    ]

  nginx:
    image: nginx:latest
    container_name: bitpapa_nginx
    restart: unless-stopped
    depends_on:
      - config_server
      - config_front
    ports:
      - "8555:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  postgres:
    image: postgres:14-alpine3.17
    container_name: bitpapa_bot_postgres
    env_file:
      - ./.env
    volumes:
      - data-postgres:/var/lib/postgresql/data

volumes:
  data-postgres:
