version: '3.8'

services:
  config_server:
    container_name: bitpapa_config_server
    build:
      context: ./app
      dockerfile: ../provision/Dockerfile.server
    env_file:
      - ./.env
    ports:
      - "8011:8003"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    command: [
      "uvicorn",
      "--host", "0.0.0.0",
      "--port", "8003",
      "--reload",
      "main:app"
    ]

  config_front:
    container_name: config_front
    build:
      context: ./config_front
      dockerfile: ../provision/Dockerfile.front
    env_file:
      - ./.env
    ports:
      - "8088:80"
    command: [
      "nginx", "-g", "daemon off;"
    ]

  postgres:
    image: postgres:14-alpine3.17
    container_name: bitpapa_bot_postgres
    env_file:
      - ./.env
    volumes:
      - data-postgres:/var/lib/postgresql/data
    ports:
      - "25438:5432"

volumes:
  data-postgres:
