"""empty message

Revision ID: 3cb7214ee5fc
Revises: 9c4abff57a36
Create Date: 2023-04-19 16:06:09.685631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb7214ee5fc'
down_revision = '9c4abff57a36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
