"""empty message

Revision ID: 477553bec210
Revises: b25d7e5b6c00
Create Date: 2023-04-28 10:32:49.268716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '477553bec210'
down_revision = 'b25d7e5b6c00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('search_amount_limit_min', sa.DECIMAL(precision=12, scale=8), server_default='0.0', nullable=False))
    op.add_column('offers', sa.Column('search_amount_limit_max', sa.DECIMAL(precision=12, scale=8), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'search_amount_limit_max')
    op.drop_column('offers', 'search_amount_limit_min')
    # ### end Alembic commands ###
