"""empty message

Revision ID: 7048a623c864
Revises: ac30d63e85d4
Create Date: 2023-04-19 16:02:29.849939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7048a623c864'
down_revision = 'ac30d63e85d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('current_price_total_duration', sa.Integer(), nullable=True))
    op.drop_column('offers', 'current_price_last_total_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('current_price_last_total_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('offers', 'current_price_total_duration')
    # ### end Alembic commands ###
