"""empty message

Revision ID: 95d68f9a13a6
Revises: 613b04491fbd
Create Date: 2023-04-19 12:55:17.148086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d68f9a13a6'
down_revision = '613b04491fbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('current_price_last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offers', sa.Column('current_price_last_response_duration', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('current_min_price_last_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offers', sa.Column('current_min_price_last_response_duration', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('current_min_price_total_duration', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('current_min_price_requests_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'current_min_price_requests_number')
    op.drop_column('offers', 'current_min_price_total_duration')
    op.drop_column('offers', 'current_min_price_last_response_duration')
    op.drop_column('offers', 'current_min_price_last_updated')
    op.drop_column('offers', 'current_price_last_response_duration')
    op.drop_column('offers', 'current_price_last_updated')
    # ### end Alembic commands ###
