"""empty message

Revision ID: 9c4abff57a36
Revises: 7048a623c864
Create Date: 2023-04-19 16:05:40.653021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4abff57a36'
down_revision = '7048a623c864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('current_price_last_request_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offers', sa.Column('current_price_last_request_block', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'current_price_last_request_block')
    op.drop_column('offers', 'current_price_last_request_time')
    # ### end Alembic commands ###
