"""empty message

Revision ID: ac30d63e85d4
Revises: b58ea5be3c74
Create Date: 2023-04-19 16:01:24.842289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac30d63e85d4'
down_revision = 'b58ea5be3c74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('current_price_last_total_duration', sa.Integer(), nullable=True))
    op.drop_column('offers', 'current_price_last_response_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('current_price_last_response_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('offers', 'current_price_last_total_duration')
    # ### end Alembic commands ###
