"""empty message

Revision ID: b58ea5be3c74
Revises: 95d68f9a13a6
Create Date: 2023-04-19 13:06:30.653173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58ea5be3c74'
down_revision = '95d68f9a13a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('current_min_price_found', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'current_min_price_found')
    # ### end Alembic commands ###
