"""empty message

Revision ID: d20093f58513
Revises: ad6e58593644
Create Date: 2023-04-13 16:03:00.591236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20093f58513'
down_revision = 'ad6e58593644'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=255), nullable=False),
    sa.Column('min_price', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('beat_price_by', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('greeting_only', sa.Boolean(), nullable=False),
    sa.Column('auto_trade_close', sa.Boolean(), nullable=False),
    sa.Column('search_price_limit_min', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('search_price_limit_max', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('search_minutes_offline_max', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_index(op.f('ix_offers_id'), 'offers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
